# Generated by Django 2.0.5 on 2018-11-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commercial_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Educational_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Embedded_systems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offline_classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Online_classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Commercial_products')),
                ('educational_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Educational_products')),
            ],
        ),
        migrations.CreateModel(
            name='Robotics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Offline_classroom')),
                ('online_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Online_classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Trending_now',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Automation')),
                ('embedded_systems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Embedded_systems')),
                ('labs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Labs')),
                ('matlab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Matlab')),
                ('robotics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Robotics')),
                ('trending_now', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Trending_now')),
            ],
        ),
    ]
